### ISSUE TITLE
Uncaught Error: channel closed

### ISSUE THREAD

**Issue by magano227** [Joezo/atom-jshint#90] opened 2015-04-15 10:46 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.191.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-jshint](https://github.com/Joezo/atom-jshint) package, v1.5.0

### Stack Trace

Uncaught Error: channel closed

```
At events.js:141

Error: channel closed
  at ChildProcess.target.send (child_process.js:396:26)
  at AtomJsHint.module.exports.AtomJsHint.run (/Users/magano/.atom/packages/atom-jshint/lib/atom-jshint.js:123:21)
  at AtomJsHint.<anonymous> (/Users/magano/.atom/packages/atom-jshint/lib/atom-jshint.js:27:16)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:110:34)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:153:19)
  at PaneContainerView.jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:64:23)
  at PaneContainerView.module.exports.PaneContainerView.onActivePaneItemChanged (/Applications/Atom.app/Contents/Resources/app/src/pane-container-view.js:53:19)
  at /Applications/Atom.app/Contents/Resources/app/src/pane-container-view.js:3:61
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app/src/pane-container.js:338:34
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:213:22)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:277:21)
  at tabs-tab.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:189:24)
  at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4430:9)
  at space-pen-ul.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4116:28)

```

### Commands

```
  6x -1:20.0 core:backspace (input.hidden-input)
     -1:11.6 core:save (input.hidden-input)
  2x -1:06.7 core:redo (input.hidden-input)
  8x -1:06.2 core:undo (input.hidden-input)
  2x -1:03.6 core:redo (input.hidden-input)
     -1:02.2 core:undo (input.hidden-input)
  2x -0:59.2 core:move-down (input.hidden-input)
  2x -0:57.2 core:move-left (input.hidden-input)
     -0:51.0 core:cut (input.hidden-input)
     -0:49.2 core:backspace (input.hidden-input)
     -0:48.8 editor:newline (input.hidden-input)
     -0:48.3 core:paste (input.hidden-input)
     -0:26.7 core:backspace (input.hidden-input)
     -0:20.1 core:save (input.hidden-input)
     -0:16.3 editor:newline (input.hidden-input)
  7x -0:14.3 core:backspace (input.hidden-input)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "afterglow-monokai-syntax"
    ],
    "disabledPackages": [
      "jshint"
    ]
  }
}
```

### Installed Packages

```coffee
# User
afterglow-monokai-syntax, v1.3.3
atom-jshint, v1.5.0
atom-terminal, v0.7.0
file-icons, v1.5.4
git-plus, v4.4.13
open-last-project, v0.4.1
project-manager, v1.15.5
react, v0.11.4

# Dev
No dev packages
```

**Comment by Joezo** [comment] 2015-05-22 14:41
Closing as a duplicate of #18

**Closed by Joezo** 2015-05-22 14:41 UTC
