### ISSUE TITLE
TextBuffer.on is deprecated.

### ISSUE THREAD

**Issue by guilhermemarconi** [Joezo/atom-jshint#101] opened 2015-05-21 20:43 UTC
TextBuffer::on is deprecated. Use event subscription methods instead.
```
TextBuffer.on (C:\Users\Marconi\AppData\Local\atom\app-0.200.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1307:16)
AtomJsHint.subscribeWith (C:\Users\Marconi\AppData\Local\atom\app-0.200.0\resources\app.asar\node_modules\emissary\lib\subscriber.js:28:32)
AtomJsHint.subscribe (C:\Users\Marconi\AppData\Local\atom\app-0.200.0\resources\app.asar\node_modules\emissary\lib\subscriber.js:63:21)
AtomJsHint.subscribeEditor (C:\Users\Marconi\.atom\packages\atom-jshint\lib\atom-jshint.js:70:12)
AtomJsHint.<anonymous> (C:\Users\Marconi\.atom\packages\atom-jshint\lib\atom-jshint.js:26:16)
atom-workspace.handler (C:\Users\Marconi\AppData\Local\atom\app-0.200.0\resources\app.asar\src\space-pen-extensions.js:110:34)
```

**Comment by Joezo** [comment] 2015-05-22 08:55
Closed as duplicate of #98

**Closed by Joezo** 2015-05-22 08:55 UTC
