### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by idali0226** [Joezo/atom-jshint#87] opened 2015-04-04 11:20 UTC
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:54:11)
AtomJsHint.updateGutter (/Users/idali/.atom/packages/atom-jshint/lib/atom-jshint.js:172:26)
```

**Comment by Joezo** [comment] 2015-05-22 08:25
closed as duplicate of #70

**Closed by Joezo** 2015-05-22 08:25 UTC
