### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by renatomarinho** [Joezo/atom-jshint#77] opened 2015-03-11 15:40 UTC
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/usr/share/atom/resources/app/src/atom.js:54:11)
AtomJsHint.updatePane (/home/s2move/.atom/packages/atom-jshint/lib/atom-jshint.js:168:9)
```

**Comment by impinball** [comment] 2015-03-17 21:27
@Joezo Please close this as a duplicate of #70.

**Closed** 2015-03-29 11:59 UTC
