### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by fabiusss** [Joezo/atom-jshint#72] opened 2015-02-17 23:20 UTC
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (C:\Users\Fabiano\AppData\Local\atom\app-0.179.0\resources\app\src\atom.js:54:11)
AtomJsHint.updateStatus (C:\Users\Fabiano\.atom\packages\atom-jshint\lib\atom-jshint.js:203:11)
```

**Comment by impinball** [comment] 2015-03-17 21:28
@Joezo Please close this as a duplicate of #70. Blame Atom's own programming for this mess.

**Closed** 2015-03-29 11:59 UTC
