### ISSUE TITLE
Uncaught Error: channel closed

### ISSUE THREAD

**Issue by magano227** [Joezo/atom-jshint#89] opened 2015-04-15 10:44 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.191.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-jshint](https://github.com/Joezo/atom-jshint) package, v1.5.0

### Stack Trace

Uncaught Error: channel closed

```
At events.js:141

Error: channel closed
  at ChildProcess.target.send (child_process.js:396:26)
  at AtomJsHint.module.exports.AtomJsHint.run (/Users/magano/.atom/packages/atom-jshint/lib/atom-jshint.js:123:21)
  at /Users/magano/.atom/packages/atom-jshint/lib/atom-jshint.js:72:16
  at later (/Applications/Atom.app/Contents/Resources/app/node_modules/scandal/node_modules/underscore/underscore.js:705:41)

```

### Commands

```
  2x -0:56.2 core:backspace (input.hidden-input)
     -0:51.9 core:move-right (input.hidden-input)
     -0:48.6 core:move-down (input.hidden-input)
     -0:48.1 core:move-left (input.hidden-input)
     -0:27.7 core:move-right (input.hidden-input)
     -0:26.6 editor:newline (input.hidden-input)
     -0:21.3 core:save (input.hidden-input)
     -0:16.5 core:backspace (input.hidden-input)
     -0:16.0 core:save (input.hidden-input)
     -0:13.4 core:move-left (input.hidden-input)
     -0:13.1 core:backspace (input.hidden-input)
     -0:11.7 core:save (input.hidden-input)
     -0:07.5 core:cut (input.hidden-input)
     -0:07.0 core:save (input.hidden-input)
     -0:04.1 core:backspace (input.hidden-input)
     -0:03.9 editor:newline (input.hidden-input)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "afterglow-monokai-syntax"
    ],
    "disabledPackages": [
      "jshint"
    ]
  }
}
```

### Installed Packages

```coffee
# User
afterglow-monokai-syntax, v1.3.3
atom-jshint, v1.5.0
atom-terminal, v0.7.0
file-icons, v1.5.4
git-plus, v4.4.13
open-last-project, v0.4.1
project-manager, v1.15.5
react, v0.11.4

# Dev
No dev packages
```

**Comment by Joezo** [comment] 2015-05-22 14:41
Closing as a duplicate of #18

**Closed by Joezo** 2015-05-22 14:41 UTC
