### ISSUE TITLE
Uncaught Error: channel closed

### ISSUE THREAD

**Issue by cgcardona** [Joezo/atom-jshint#105] opened 2015-06-02 19:53 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.204.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-jshint](https://github.com/Joezo/atom-jshint) package, v2.0.0

### Stack Trace

Uncaught Error: channel closed

```
At events.js:141

Error: channel closed
  at ChildProcess.target.send (child_process.js:396:26)
  at AtomJsHint.module.exports.AtomJsHint.run (/Users/ccardona/.atom/packages/atom-jshint/lib/atom-jshint.js:105:21)
  at AtomJsHint.<anonymous> (/Users/ccardona/.atom/packages/atom-jshint/lib/atom-jshint.js:66:16)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1219:25

```

### Commands

```
  2x -0:17.4.0 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:15.6.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  2x -0:15.5.0 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:15.1.0 vim-mode:put-after (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:14.6.0 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:13.6.0 vim-mode:activate-command-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  2x -0:13.4.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:12.7.0 vim-mode:insert-below-with-newline (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:10.2.0 vim-mode:activate-command-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:09.9.0 vim-mode:reset-command-mode (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  2x -0:09.5.0 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  2x -0:08.8.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  2x -0:08.5.0 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:07.9.0 core:save (atom-text-editor.editor.vim-mode.is-focused.command-mode)
 37x -0:03.5.0 blur (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:01.2.0 vim-mode:insert-below-with-newline (atom-text-editor.editor.vim-mode.command-mode.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.9
atom-jshint, v2.0.0
highlight-selected, v0.9.3
minimap, v4.9.2
minimap-autohide, v0.10.0
minimap-bookmarks, v0.1.0
minimap-color-highlight, v4.1.4
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.3
minimap-highlight-selected, v4.3.0
minimap-selection, v4.2.0
vim-mode, v0.49.0

# Dev
No dev packages
```

**Comment by hongkongkiwi** [comment] 2015-06-04 07:35
same problem here.

**Comment by Joezo** [comment] 2015-06-04 07:54
Yeah i'm seeing this as well, still not sure why the child process is crashing. See #63 for reproduction instructions, i'm going to close this as a duplicate of that. I should have some free time tomorrow to look at this, sorry!

**Closed by Joezo** 2015-06-04 07:54 UTC
